### ISSUE TITLE
New to Sketch

### ISSUE THREAD

**Issue by rherring** [michaellee/iOS-iMessage-Stickers-Icon-Sketch-Template#1]
I've been using Photoshop since the 1st version, but I'm SUPER new to Sketch... as in, I've purchased and downloaded it, but haven't done anything past that.

I've opened up your file, but how/where do I upload my Image, in order to get the image to populate into all of the icons?

Thanks.

**Comment by michaellee** [comment]
Hey @rherring 

So, the icons have to be added to each **Artboard** on the left hand side. Each Artboard coincides with a needed icon size for Xcode. As long as those are populated, you can go to **File > Export...** and the Sketch template will automatically generate the different sizes and file names that you'll need for Xcode.

**Comment by rherring** [comment]
Okay, so it can't be added to one Artboard, which then applies it to all the others at the correct size.

**Comment by michaellee** [comment]
That's right @rherring 

I'm not sure if Sketch could do that. Perhaps it could do that but the template that I've made is assuming that a logo is adjusted to each Artboard.
