### ISSUE TITLE
[sticker pack] Loot Llamas Stickers

### ISSUE THREAD

**Issue by wongjustin99** [michaellee/iOS-iMessage-Stickers-Icon-Sketch-Template#3]
Hi Michael, 

Thanks for the template. I also went through the same path as the other posters. 

Very useful! I adapted this to Affinity Designer. 

https://itunes.apple.com/gb/app/loot-llamas-battle-royale/id1325952717?mt=8

https://twitter.com/fulltimeuser

**Comment by michaellee** [comment]
Hey hey @wongjustin99 these stickers look great! Congrats on putting it out there. I hope you have much success with them :)

Very cool that you adapted the template to Affinity Designer. I have never used the app myself. But by putting it out there I hope more folks will find it helpful. Cheers!
